language: java
env:
  - SCALA_VERSION=2.11.7
    - SCALA_VERSION=2.12.4
os:
  - osx
script:
  - curl -Ls https://git.io/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt
  - ./sbt "++$SCALA_VERSION" test
matrix:
  include:
    - env: SCALA_VERSION=2.11.7
      os: linux
      jdk: oraclejdk7
    - env: SCALA_VERSION=2.10.5
      os: linux
      jdk: oraclejdk8
