language: java
env: 
    - SCALA_VERSION=2.10.4 
    - SCALA_VERSION=2.12.4
os: 
    -osx
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; thencurl -Ls https://git.io/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt ; fi
script: 
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ~/bin/sbt "++$SCALA_VERSION" test    ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux"    ]]; then sbt "++$SCALA_VERSION" test    ; fi
matrix:
    include:
        - os: linux
          sudo: required
          jdk: oraclejdk8
          env: SCALA_VERSION= 2.10.4
        - os: linux
          sudo: required
          jdk: oraclejdk8
          env: SCALA_VERSION= 2.12.4