language: java
env: 
    - SCALA_VERSION=2.10.4 
    - SCALA_VERSION=2.12.4
os: 
    -osx
install: 
    - curl -Ls https://git.io/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt

matrix:
    include:
        - os: linux
          sudo: required
          jdk: oraclejdk8
          scala:2.10.4