language: scala
env:
    - SCALA_VERSION=2.10.4
    - SCALA_VERSION=2.12.4
os:
    -linux
install:
    - curl -Ls https://git.io/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux"    ]]; then sbt "++$SCALA_VERSION" test
          else ~/bin/sbt "++$SCALA_VERSION" test    ; fi
matrix:
    include:
        - os: osx
          language: java
          sudo: required
          scala: 2.10.4
        - os: osx
          language: java
          sudo: required
          jdk: oraclejdk8
          scala: 2.12.4